#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend cryptotechcoder
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 523699-web-01 54.236.48.82:80 check
    server 523699-web-02 54.237.22.20:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
